export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const GET_BOOKMARKS = 'GET_BOOKMARKS';

export const CHANGE_UNIT = 'CHANGE_UNIT';

export const DETAILED_FORECAST = 'DETAILED_FORECAST';
export const THEME = 'THEME';